### ISSUE TITLE
Indentation in the assembly editor is inconsistent

### ISSUE THREAD

**Issue by Jorgeelalto** [wepsim/wepsim#400]
Inserting an indentation with the tab key creates an horizontal tab but selecting code and then trying to indentate it pressing tab inserts two spaces before all lines.

**Comment by wepsim** [comment]
What 'Editor mode' are you using in the configuration?
Are you using the default, VIM, Emacs, etc.?

**Comment by wepsim** [comment]
Now the block indentation has been configured in the same way that the tab. indentation.
Thanks for the advise.

Please remember that editing is not the main goal of WepSIM because you could edit
in your favorite editor and copy&paste into the existing one (codemirror).
