### ISSUE TITLE
Simulation does not work

### ISSUE THREAD

**Issue by bodgergely** [wepsim/wepsim#426]
After compiling the microcode and the assembly when I go to the Simulation tab none of the 'Run', and the micro/macro code single stepping works:

Does not work under Chrome nor Firefox.

From Google Chrome Dev Console:

10common-content.js:99 Uncaught TypeError: Cannot read property 'clientWidth' of null
common-content.js:99 Uncaught TypeError: Cannot read property 'clientWidth' of null
    at Object.getSize (common-content.js:99)
    at doc-end.js:6
    at onPageDataReady (doc-start.js:35)
    at doc-end.js:1
common-content.js:99 Uncaught TypeError: Cannot read property 'clientWidth' of null
    at Object.getSize (common-content.js:99)
    at doc-end.js:6
    at onPageDataReady (doc-start.js:35)
    at doc-end.js:1
The FetchEvent for "https://acaldero.github.io/wepsim/" resulted in a network error response: the promise was rejected.
min.wepsim_pwa.js:191 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
    at min.wepsim_pwa.js:191
The FetchEvent for "https://acaldero.github.io/wepsim/sim_hw/sim_hw_ep/controlunit6.svg" resulted in a network error response: the promise was rejected.
The FetchEvent for "https://acaldero.github.io/wepsim/sim_hw/sim_hw_ep/processor6.svg" resulted in a network error response: the promise was rejected.
2min.wepsim_pwa.js:191 Uncaught (in promise) TypeError: Failed to execute 'fetch' on 'ServiceWorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
    at min.wepsim_pwa.js:191

**Comment by acaldero** [comment]
Thanks bodgergely, it is true that after accepting the pull-request from wepsim-acadero repository the was one missing step to prepare the wepsim one.

Please check again, at least for me now work (Firefox/Chrome68 x Android/iOS/Windows)
BUT the first time (because it has to re-fill the browser cache) it takes a bit of time to be ready.

**Comment by bodgergely** [comment]
Thanks, the nightly builds seems to work now.
